acceuil:
    path: /
    controller: App\Controller\Forms\LoginController::accueil

hello:
    path: /hello/{prenom}
    controller: App\Controller\HelloWorldController::hello
    requirements:
        prenom: '[a-zA-Z]+'

helloListe:
    path: /helloListe
    controller: App\Controller\HelloWorldController::helloListe

form:
    path: /form
    controller: App\Controller\HelloWorldController::form
    methods: GET

formReceive:
    path: /form
    controller: App\Controller\HelloWorldController::form_receive
    methods: POST

login:
    path: /login
    controller: App\Controller\Forms\LoginController::login
    methods: GET

loginVerif:
    path: /login
    controller: App\Controller\Forms\LoginController::loginPost
    methods: POST