acceuil:
    path: /
    controller: App\Controller\Forms\LoginController::accueil

hello:
    path: /hello/{prenom}
    controller: App\Controller\HelloWorldController::hello
    requirements:
        prenom: '[a-zA-Z]+'

helloListe:
    path: /helloListe
    controller: App\Controller\HelloWorldController::helloListe

form:
    path: /form
    controller: App\Controller\HelloWorldController::form
    methods: GET

formReceive:
    path: /form
    controller: App\Controller\HelloWorldController::form_receive
    methods: POST

login:
    path: /login
    controller: App\Controller\Forms\LoginController::login
    methods: GET

loginVerif:
    path: /login
    controller: App\Controller\Forms\LoginController::loginPost
    methods: POST

crerCake:
    path: /cakeAdd
    controller: App\Controller\CakeController::createCake

getCake:
    path: /cakeGet/{id}
    controller: App\Controller\CakeController::getCakeById

crerUser:
    path: /userAdd
    controller: App\Controller\UserController::createUser

crerRole:
    path: /roleAdd
    controller: App\Controller\UserController::createRole

affectRole:
    path: /affectRole/{rid}-{uid}
    controller: App\Controller\UserController::affectRole

afficheUser:
    path: /afficherUtilisateur
    controller: App\Controller\UserController::afficherUser

connexionUser:
    path: /connexionUser
    controller: App\Controller\UserController::connexionUser
    methods: GET

verifUser:
    path: /connexionUser
    controller: App\Controller\UserController::verificationUser
    methods: POST